### ISSUE TITLE
Framework Laptop EC for Intel 12th Gen Core Processors

### ISSUE THREAD

**Issue by potentialuser54** [FrameworkComputer/EmbeddedController#14]
The instructions in the README only covers building the EC firmware for 11th Gen Core Processors. Could you provide instructions for the upcoming laptops which includes 12th Gen Processors

**Comment by kiram9** [comment]
@potentialuser54 we will be releasing the EC firmware for 12th gen before the 12th gen hardware is released.

**Comment by potentialuser54** [comment]
Glad to hear that.
